apiVersion: v1
kind: Pod
metadata:
  name: movie-db
spec:
  containers:
    - name: movie-db
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      env:
        - name: POSTGRES_USER
          value: {{ .Values.database.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password }}
        - name: POSTGRES_DB
          value: {{ .Values.database.db }}
      volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: movie-db-storage
  volumes:
    - name: movie-db-storage
      persistentVolumeClaim:
        claimName: movie-db-pvc