apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: jenkins.cours-datascientest-1.cloudns.ch/api/v1/movies
    http:
      paths:
      - path: /api/vi/movies
        pathType: Prefix
        backend:
          service:
            name: movie-service
            port:
              number: 8000
