apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2  # Réécriture de l'URL
spec:
  ingressClassName: nginx  # Définit NGINX comme classe d'Ingress
  rules:
  - host: jenkins.cours-datascientest-1.cloudns.ch  # Hôte sans chemin
    http:
      paths:
      - path: /api/v1/movies(/|$)(.*)  # Le chemin est ici
        pathType: Prefix
        backend:
          service:
            name: movie-service
            port:
              number: 8000
