apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: dev  
spec:
  type: {{ .Values.service.type }}
    ports:
      - port: {{ .Values.service.port }}
        targetPort: http
        protocol: TCP
        name: http
