replicaCount: 1

image:
  repository: swezwalid/movie-service
  tag: ""

service:
  type: ClusterIP
  port: 8000

hpa:
  minReplicas: 1
  maxReplicas: 6
  cpu: 70
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  
  hosts:
    - host: jenkins.cours-datascientest-1.cloudns.ch  
      paths:
        - path: /api/v1/movies/
          pathType: Prefix
  tls:
    - hosts:
        - jenkins.cours-datascientest-1.cloudns.ch
      secretName: movie-service-tls

databaseUri: postgresql://movie_db_username:movie_db_password@moviedb:5432/movie_db_dev

