replicaCount: 1

image:
  repository: swezwalid/movie-service
  tag: ""

service:
  type: ClusterIP
  port: 8000

hpa:
  minReplicas: 1
  maxReplicas: 6
  cpu: 70

databaseUri: postgresql://movie_db_username:movie_db_password@moviedb:5432/movie_db_dev

