replicaCount: 3

image:
  repository: swezwalid/cast-service
  tag: ""

service:
  type: ClusterIP
  port: 8000

hpa:
  minReplicas: 3
  maxReplicas: 6
  cpu: 70

databaseUri: postgresql://cast_db_username:cast_db_password@castdb:5432/cast_db_dev
