replicaCount: 3

image:
  repository: swezwalid/cast-service
  tag: latest

service:
  type: ClusterIP
  port: 8000

hpa:
  minReplicas: 3
  maxReplicas: 6
  cpu: 70


ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  
  hosts:
    - host: jenkins.cours-datascientest-1.cloudns.ch  
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - jenkins.cours-datascientest-1.cloudns.ch
      secretName: cast-service-tls

databaseUri: postgresql://cast_db_username:cast_db_password@castdb:5432/cast_db_dev
