apiVersion: v1
kind: Service
metadata:
  name: castdb
  namespace: dev 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}